[env:waveshare_p4_poe]
; Nutze den pioarduino Fork
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32-p4-evboard
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS="${PROJECT_DIR}/sdkconfig.defaults"
framework = arduino

; Exakte Hardware-Daten des Waveshare Boards überschreiben
board_upload.flash_size = 32MB
board_build.flash_mode = dio
; board_build.arduino.memory_type = p4_32mb_psram  <- breaks sdkconfig.h path resolution

; Monitor Einstellungen
monitor_speed = 115200

; USB CDC Flags für ESP32-P4 (Routet Serial auf den Hardware JTAG CDC Port)
; build_flags =
;   -D ARDUINO_USB_MODE=1
;   -D ARDUINO_USB_CDC_ON_BOOT=1

; rs-engine-core FFI
build_flags =
    -I${PROJECT_DIR}/../rs-engine/ffi/include

extra_scripts = pre:link_rust.py